version: '3.8'

services:
  telegram-bot:
    build: .
    container_name: telegram-echo-bot
    env_file:
      - .env
    volumes:
      - .:/app
    restart: unless-stopped
    command: ruby bot.rb